config/routes.rb
Clearwater::Application.routes.draw do

  get 'admin' => 'admin#show'
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    resources :reservations, only: [:new, :create], controller: :slots
  end
  get '/user/:user_id/reservations/labels', to: "slots#newlabels",
    as: 'reservations_newlabels'
  patch '/user/:user_id/reservations/labels', to: "slots#setlabels", 
    as: 'reservations_setlabels'
  namespace :admin do
    resources :seasons
    resources :dates, controller: 'fish_dates' do
      resources :reservations, only: [:new, :create], controller: :slots   
    end
    resources :reservations, only: [:edit, :update, :destroy], controller: :slots   
    resources :users do
      member do
        get 'copy'
      end
    end
  end

  root "sessions#new"

end

app/models/slot.rb
class Slot < ActiveRecord::Base
  belongs_to :fish_date
  belongs_to :user
  validates_presence_of :label

  def owner
    if !user
      ''
    else
      namestr = user.name
      if label == "self"
        namestr
      else
        label + ' (Guest of: ' + namestr + ')'
      end
    end
  end
  def guest
    if !user || label == 'self'
      ''
    else
      label
    end
  end

end

app/controllers/admin/slots_controller.rb
class Admin::SlotsController < ApplicationController
  before_filter :authenticate

  def user_authorized?
    current_user.admin
  end

  def new
    # check authorization manually
    if !user_authorized?
      raise Pundit::NotAuthorizedError
    end
    @date = FishDate.find(params[:date_id])
    @display = :users
    @users = User.where(admin: false)
  end

  def create
    # check authorization manually
    if !user_authorized?
      raise Pundit::NotAuthorizedError
    end
    session[:reserve_date] = params[:date_id]
    session[:reserve_slots] = params[:num_slots]
    # get selected user from radio button
    if params[:user] == 'admin'
      user = current_user
    else
      user = User.find(params[:user])
    end
    redirect_to reservations_newlabels_path(user)
  end

  def edit
    # check authorization manually
    if !user_authorized?
      raise Pundit::NotAuthorizedError
    end
    @slot = Slot.find(params[:id])
    @user = @slot.user
    @date = @slot.fish_date
  end

  def update
    # check authorization manually
    if !user_authorized?
      raise Pundit::NotAuthorizedError
    end
    slot = Slot.where(id: params[:id]).includes(:fish_date, :user).first
    newlabel = ''
    case params[:newlabel]
      when /self/
        newlabel = 'self'
      when /new/
        newlabel = params[:newlabel_guest]
    end
    if newlabel != slot.label
      slot.label = newlabel
      slot.save
    end
    redirect_to admin_date_path(slot.fish_date)
  end
  def destroy
    # check authorization manually
    if !user_authorized?
      raise Pundit::NotAuthorizedError
    end
    slot = Slot.find(params[:id])
    date = slot.fish_date
    slot.destroy
    redirect_to admin_date_path(date)
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_filter :authenticate
  def user_authorized?
    params[:user_id].to_i == session[:user_id] || current_user.admin
  end
    
    
  def new
    # check authorization manually
    if !user_authorized?
      raise Pundit::NotAuthorizedError
    end
    @user = User.find(params[:user_id])
    @display = :dates
    @dates = FishDate.where(season: current_season)
  end

  def create
    user = User.find(params[:user_id])
    # check authorization manually
    if !user_authorized?
      raise Pundit::NotAuthorizedError
    end
    session[:reserve_date] = params[:fish_date]
    session[:reserve_slots] = params[:num_slots]
    redirect_to reservations_newlabels_path(user)
  end

  def newlabels
    @user = User.find(params[:user_id])
    # check authorization manually
    if !user_authorized?
      raise Pundit::NotAuthorizedError
    end
    reserve_date = session[:reserve_date]
    reserve_slots = session[:reserve_slots].to_i
    if reserve_date && reserve_slots
      @date = FishDate.find(reserve_date)
      if @date.available(true) < reserve_slots
        flash[:alert] = "Slots are not available."
        session.delete(:reserve_date)
        session.delete(:reserve_slots)
        redirect_to new_user_reservation_path(@user) and return
      end
      @num_slots = reserve_slots
      render :slot_labels and return
    else
      flash[:alert] = "Error during reservation.  Please try again."
      session.delete(:reserve_date)
      session.delete(:reserve_slots)
      redirect_to new_user_reservation_path(user)
    end
  end

  def setlabels
    user = User.find(params[:user_id])
    # check authorization manually
    if !user_authorized?
      raise Pundit::NotAuthorizedError
    end
    reserve_date = session[:reserve_date]
    reserve_slots = session[:reserve_slots].to_i
    session.delete(:reserve_date)
    session.delete(:reserve_slots)
    if reserve_date
      date = FishDate.find(reserve_date) 
    else
      flash[:alert] = "Error during reservation.  Please try again."
      redirect_to new_user_reservation_path(user) and return
    end
    new_guest = false
    reserve_slots.times do |i|
      label = ''
      case params["label_#{i}"]
      when 'self'
        label = 'self'
      when 'select'
        label = params["label_select_#{i}"]
      when 'new'
        guest = params["label_new_#{i}"]
        label = guest
        user.guests << guest
        new_guest = true
      end
      Slot.create!(user: user, fish_date: date, label: label)
    end
    if new_guest
      user.guests.sort!
      user.save
    end
    if !user.admin && user == current_user
      redirect_to user_path(user)
    else
      redirect_to admin_date_path(date)
    end
  end
end

app/helpers/admin/slots_helper.rb
module Admin::SlotsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_choose_date_form.html.haml
%h2 Choose a date:

= form_tag user_reservations_path, method: :post do

  - @dates.each do |date|
    - if !date.fully_booked? 
      = radio_button_tag 'fish_date', date.id
      = date.day.strftime("%b %d, %Y (%A)") 
      = ' -- Available slots: '
      = date.available
    %br/

  %p
    = label_tag :num_slots, "Number of Slots"
    = text_field_tag :num_slots
  %p
    = submit_tag "Request"

app/views/slots/_choose_user_form.html.haml
%h2 Choose a user:

= form_tag admin_date_reservations_path, method: :post do

  - @users.each do |user|
    - if !user.fully_booked? 
      = radio_button_tag 'user', user.id

  %p
    = label_tag :num_slots, "Number of Slots"
    = text_field_tag :num_slots
  %p
    = submit_tag "Request"

app/views/slots/create.html.haml
%h1 Slots#create
%p Find me in app/views/slots/create.html.haml

app/views/slots/destroy.html.haml
%h1 Slots#destroy
%p Find me in app/views/slots/destroy.html.haml

app/views/slots/slot_labels.html.haml
%h2 Slot Assignments for #{@date.print_full}

%p
  Please provide a name for each reserved slot. <br>
  You can:
%ul
  %li Choose 'self' for yourself, 
  %li Choose a guest from your previous guests (if any), or
  %li Provide a new guest name (which will be added to your list).

= form_tag reservations_setlabels_path, method: :patch do
  - @num_slots.times do |index|
    .chooselabel
      = radio_button_tag "label_#{index}", 'self', true
      Self <br>
      = radio_button_tag "label_#{index}", 'select'
      Choose a guest: 
      = select_tag "label_select_#{index}", options_for_select(@user.guests)
      <br>
      = radio_button_tag "label_#{index}", 'new'
      = label_tag "label_new_#{index}", "Guest name: "
      = text_field_tag "label_new_#{index}"

  %p
    = submit_tag "Submit"