config/routes.rb
Clearwater::Application.routes.draw do

  get 'admin' => 'admin#show'
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    resources :reservations, only: [:new, :create], controller: :slots
  end
  get '/user/:user_id/reservations/labels', to: "slots#newlabels",
    as: 'reservations_newlabels'
  patch '/user/:user_id/reservations/labels', to: "slots#setlabels", 
    as: 'reservations_setlabels'
  namespace :admin do
    resources :seasons
    resources :dates, controller: 'fish_dates' do
      resources :reservations, only: [:new, :create], controller: :slots   
    end
    resources :reservations, only: [:edit, :update, :destroy], controller: :slots   
    resources :users do
      member do
        get 'copy'
      end
    end
  end

  root "sessions#new"

end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :fish_dates
  has_many :users
  validates :start_month, numericality: {greater_than: 0, less_than: 13}
  validates :end_month, numericality: {greater_than: 0, less_than: 13}
  validates :year, numericality: {greater_than: 0}
  validates :slot_limit, numericality: {greater_than: 0}

  def start_date
    Date.new(year, start_month)
  end
  def end_date
    if end_month >= start_month
      Date.new(year, end_month, -1)
    else
      Date.new(year+1, end_month, -1)
    end
  end

  def in_season?(date)
    date >= start_date && date <= end_date
  end
  
  def name
    if end_month <= start_month
      "#{year}-#{(year+1)%100}"
    else
      "#{year}"
    end
  end

end

app/controllers/admin/seasons_controller.rb
class Admin::SeasonsController < ApplicationController
  before_filter :authenticate

  def index
    authorize Season.new
    @seasons = Season.order(year: :desc, start_month: :desc)
    @current = find_current_season()
  end

  def show
    @season = Season.find(params[:id])
    if @season
      authorize @season
      @dates = @season.fish_dates
      @users = @season.users
      @is_current = @season.id == current_season.id
    else
      @dates = nil
      @users = nil
      @is_current = nil
    end
  end

  def new
    authorize Season.new
  end

  def create
    season = Season.new
    authorize season
    season.year = params[:date][:year].to_i
    season.start_month = params[:date][:start_month].to_i
    season.end_month = params[:date][:end_month].to_i
    season.slot_limit = params[:slot_limit].to_i
    if season.save
      flash.notice = "Season #{season.year} created."
      redirect_to admin_seasons_path
    else
      flash.now[:warning] = "Unable to create season. "
      season.errors.messages.each do | attr, msg |
        season.errors.full_messages_for(attr).each do | m |
          flash.now[:warning] << m
        end
      end
      render :new
    end
  end

  def update
    Properties.instance.update_attribute(:current_season_id, params[:id])
    session[:season_id] = nil if session[:season_id]
    redirect_to admin_seasons_path
  end

  def destroy
    @season = Season.find(params[:id])
    if @season 
      if @season.id == current_season.id
        flash.now[:warning] = "Cannot destroy current season."
        redirect_to admin_seasons_path
      else
        year = @season.year
        users = @season.users
        dates = @season.fish_dates
        users.each do |u|
          u.destroy
        end
        dates.each do |d|
          d.destroy
        end
        @season.destroy
        flash.notice = "Season #{year} deleted."
        redirect_to admin_seasons_path
      end
    else
      flash.now[:warning] = "ERROR: no such season -- cannot destroy."
      redirect_to admin_seasons_path
    end
  end
end

app/helpers/admin/seasons_helper.rb
module Admin::SeasonsHelper
end

app/views/admin/seasons/_fish_date.html.haml
%tr
  %td.date= fish_date.day.strftime("%b %-d, %Y (%A)")
  %td.slots= fish_date.slot_limit
  - if fish_date.slots.count < fish_date.slot_limit
    %td.slots.used= fish_date.slots.count
  - else
    %td.slots.full= fish_date.slots.count

  %td.link= link_to "Show", admin_date_path(fish_date)
  %td.link= link_to "Change Slot Limit", edit_admin_date_path(fish_date)
  %td.link= link_to "Delete", admin_date_path(fish_date), 
              method: :delete,
              data: {confirm: "Deleting #{fish_date.day.to_s} -- are you sure?"},
              id: "delete_#{fish_date.id}"

app/views/admin/seasons/_fish_dates_table.html.haml
%table.admindates
  %thead
    %tr
      %th.date Date
      %th.slots Slots Avail
      %th.slots Slots Taken
  %tbody
    = render fish_dates

app/views/admin/seasons/_user.html.haml
%tr
  %td.name= user.fullname
  %td.email= user.email
  %td.phone= user.phone
  -if !user.admin?
    %td.slots= user.purchased
    - if user.used < user.purchased
      %td.slots.used= user.used
    -else
      %td.slots.used.full= user.used
  %td.link= link_to "Edit", edit_admin_user_path(user)
  - if !user.admin?
    %td.link= link_to "Show", user_path(user)
  %td.link= link_to "Delete", admin_user_path(user), 
              method: :delete,
              data: {confirm: "Deleting #{user.email} -- are you sure?"},
              id: "delete_#{user.id}"

app/views/admin/seasons/_users_table.html.haml
%table.adminusers
  %thead
    %tr
      %th Name
      %th Email
      %th Phone
      %th Slots
      %th Used
  %tbody
    = render users, :in_current => true

app/views/admin/seasons/index.html.haml
%h1 Seasons

%p
  =link_to "Add New Season", new_admin_season_path
  %br
  =link_to "Admin Home", admin_path


%table.adminseasons
  %tbody
  = div_for(@seasons) do |season|
    %tr
      %td #{season.name}
      %td #{season.start_date.strftime('%b \'%y')} - #{season.end_date.strftime('%b \'%y')}
      %td.link= link_to "Show", admin_season_path(season)
      -if current_season() && season.id == current_season().id
        %td.current(colspan="2") [CURRENT]
      -else
        %td.link= link_to "Delete", admin_season_path(season), 
                  method: :delete,
                  data: {confirm: "Deleting Season #{season.year} -- are you sure?"},
                  id: "delete_#{season.id}"
        %td.link= link_to "Set as Current", admin_season_path(season),
                  method: :put,
                  id: "put_#{season.id}"

%p
  Deleting a season removes all dates, reservations, and users for that season.
  %br
  If a user is associated with another season, that info will not be deleted.
  %br
  The current season cannot be deleted.  

app/views/admin/seasons/new.html.haml
%h1 Create New Season

= form_tag(admin_seasons_path, method: :post) do
  %p
    = label_tag :year, "Year"
    = select_year(Date.today)
  %p
    = label_tag :start_month, "Start Month"
    = select_month(10, field_name: :start_month)
  %p
    = label_tag :end_month, "End Month"
    = select_month(4, field_name: :end_month)
  %p
    = label_tag :slot_limit, "Slot Limit"
    = text_field_tag :slot_limit, '', size: 5
  %p
    = submit_tag "Create"

app/views/admin/seasons/show.html.haml
%h1 #{@season.name}
%h2 #{@season.start_date.strftime('%b \'%y')} - #{@season.end_date.strftime('%b \'%y')}

-if @is_current
  =link_to "Add New Date", new_admin_date_path
  %br
  =link_to "Add New User", new_admin_user_path
  %br

=link_to "Admin Home", admin_path

%h3 Dates

= render 'fish_dates_table', :fish_dates=> @dates

%h3 Users

= render 'users_table', :users=> @users