config/routes.rb
Clearwater::Application.routes.draw do

  get 'admin' => 'admin#show'
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    resources :reservations, only: [:new, :create], controller: :slots
  end
  get '/user/:user_id/reservations/labels', to: "slots#newlabels",
    as: 'reservations_newlabels'
  patch '/user/:user_id/reservations/labels', to: "slots#setlabels", 
    as: 'reservations_setlabels'
  namespace :admin do
    resources :seasons
    resources :dates, controller: 'fish_dates' do
      resources :reservations, only: [:new, :create], controller: :slots   
    end
    resources :reservations, only: [:edit, :update, :destroy], controller: :slots   
    resources :users do
      member do
        get 'copy'
      end
    end
  end

  root "sessions#new"

end

app/models/fish_date.rb
class FishDate < ActiveRecord::Base
  belongs_to :season
  validates_presence_of :season_id
  has_many :slots
  validates_presence_of :day
  validates_numericality_of :slot_limit
  validate :day_in_season?

  def fully_booked?(force=false)
    available(force) <= 0
  end
  def available(force=false)
    reload if force
    slot_limit - slots.count
  end

  def print_num
    day.to_s
  end
  def print_full
    day.strftime("%b %-d, %Y (%A)")
  end
  def print_short
    day.strftime("%b %-d")
  end

  def day_in_season?
    if (season && !season.in_season?(day))
      errors.add(:day, 'must be a valid date') 
    end
  end
end

app/controllers/admin/fish_dates_controller.rb
class Admin::FishDatesController < ApplicationController
  before_filter :authenticate

  def show
    @date = FishDate.find(params[:id])
  end

  def index
    authorize FishDate.new
    @season = current_season
    @dates = FishDate.where(season: @season)
  end

  def new
    authorize FishDate.new
    @start_date = current_season.start_date
    @end_date = current_season.end_date
    latest = FishDate.where(season: current_season).order(day: :desc).first
    @last_date = latest.day if latest
  end

  def create
    fdate = FishDate.new(season: current_season)
    authorize fdate
    if params[:datestr]
      day = Date.strptime(params[:datestr], '%Y-%m-%d')
    else
      day = Date.new(params[:date][:year].to_i, params[:date][:month].to_i, 
                     params[:date][:day].to_i)
    end
    if day && day >= current_season.start_date && day <= current_season.end_date
      fdate.day = day
      if params[:slots]
        fdate.slot_limit = params[:slots]
      else
        fdate.slot_limit = current_season.slot_limit
      end
      if fdate.save
        flash[:notice] = "Date added to current season."
      else
        flash[:warning] = "Unable to create date. "
        fdate.errors.messages.each do | attr, msg |
          fdate.errors.full_messages_for(attr).each do | m |
            flash[:warning] << m
          end
        end
      end
    else
      flash[:alert] = "Date not within current season."
    end
    redirect_to admin_dates_path
  end

  def edit
    @date = FishDate.find(params[:id])
    authorize @date
  end

  def update
    fdate = FishDate.find(params[:id])
    authorize fdate
    new_limit = params[:slot_limit].to_i
    if new_limit && new_limit != fdate.slot_limit
      slot_count = fdate.slots.count
      if new_limit >= slot_count
        fdate.slot_limit = new_limit
      else
        # if new limit is smaller than the number of slots...
        fdate.slot_limit = slot_count
        flash[:warning] = "Cannot reduce slots below number of existing reservations."
      end
      fdate.save
    end
    redirect_to admin_dates_path
  end

  def destroy
    fdate = FishDate.find(params[:id])
    if fdate
      authorize fdate
      flash[:notice] = "Date #{fdate.day.to_s} deleted."
      fdate.destroy
    end
    redirect_to admin_dates_path
  end

end

app/helpers/admin/fish_dates_helper.rb
module Admin::FishDatesHelper
end

app/views/admin/fish_dates/_date_slot_list.html.haml
-# @slots is collection of non-empty slots (may be nil)
-# @limit is number of slots allowed for this list

- count = 0
- count = slots.count if slots


%table.slotslist

  - if slots
    - slots.each do |s|
      %tr
        %td.owner= s.owner
        %td.change
          = link_to "Change Name", edit_admin_reservation_path(s),
                    id: "change_name_#{s.id}"
        %td.delete
          = link_to "Delete", admin_reservation_path(s),
                    data: {confirm: 'Deleting reservation -- are you sure?'},
                    id: "delete_#{s.id}", method: :delete

  - (limit - count).times do
    %tr
      %td.empty Not filled


        

app/views/admin/fish_dates/edit.html.haml
%h1 Change slot limit for #{@date.print_short}

= form_tag admin_date_path(@date), method: :patch do
  = label_tag :slot_limit, "Number of slots:"
  = text_field_tag :slot_limit, @date.slot_limit

  = submit_tag "Change Limit"

app/views/admin/fish_dates/index.html.haml
%h1 Dates for season: #{@season.name}

= link_to "Add New Date", new_admin_date_path
%br
= link_to "Admin Home", admin_path

%h2 
  Dates

= render 'fish_dates_table', { fish_dates: @dates }

app/views/admin/fish_dates/new.html.haml
%h1 Add new date to season: #{current_season.year}

= form_tag admin_dates_path, method: :post do

  #newdate{data: {min_date: @start_date, max_date: @end_date,
                  default_date: @last_date}}
    = select_month(@start_date.month, use_short_month: true)
    = select_day(1)
    = select_year(@start_date.year,
                  start_year: @start_date.year,
                  end_year: @end_date.year)

  %p
    = label_tag :slots, "Number of Slots"
    = text_field_tag :slots, current_season.slot_limit, size: 4

  %p
    = submit_tag "Add Date"

app/views/admin/fish_dates/show.html.haml
%h1 Slots for #{@date.print_short}

= render partial: 'date_slot_list', 
  locals: { slots: @date.slots, limit: @date.slot_limit }

%br
= link_to "Make Reservation", new_admin_date_reservation_path(@date)
%br
= link_to "Admin Home", admin_path