config/routes.rb
Clearwater::Application.routes.draw do

  get 'admin' => 'admin#show'
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    resources :reservations, only: [:new, :create], controller: :slots
  end
  get '/user/:user_id/reservations/labels', to: "slots#newlabels",
    as: 'reservations_newlabels'
  patch '/user/:user_id/reservations/labels', to: "slots#setlabels", 
    as: 'reservations_setlabels'
  namespace :admin do
    resources :seasons
    resources :dates, controller: 'fish_dates' do
      resources :reservations, only: [:new, :create], controller: :slots   
    end
    resources :reservations, only: [:edit, :update, :destroy], controller: :slots   
    resources :users do
      member do
        get 'copy'
      end
    end
  end

  root "sessions#new"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  # every user belongs to a season, except for admin users
  belongs_to :season

  has_many :slots
  has_many :fish_dates, through: :slots
  validates_presence_of :password_digest
  validates :admin, inclusion: { in: [true, false] }
  validates_presence_of :email
  validates_format_of :email, 
     with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/
  with_options unless: :admin? do |user|
    user.validates_presence_of :season_id
    user.validates_uniqueness_of :email, scope: :season_id,
          message: 'matches an existing user within the season.'
  end
  with_options if: :admin? do |user|
    user.validates_uniqueness_of :email,
          message: 'matches an existing admin user.'
  end
  
  serialize :guests, Array

  def name
    fullname || email
  end

  def fullname
    @fullname = create_name
  end

  def create_name
    if firstname && lastname
      [ firstname, lastname ].reject(&:empty?).join(' ')
    else
      firstname || lastname 
    end
  end

  def used
    slots.count
  end
  def available
    purchased - slots.count
  end

  def fully_booked?
    slots.count >= purchased
  end

  def current?
    season.id == current_season.id
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate

  def index
    authorize User.new
    @admin_users = User.where(admin: true)
    @seasons = Season.all.sort {|a,b| b.year <=> a.year }
    @current = current_season

  end

  def new
    authorize User.new
  end

  def create
    user = User.new
    authorize user
    # when copying into current season, these parameters should be set 
    user.firstname = params[:firstname] if params[:firstname]
    user.lastname = params[:lastname] if params[:lastname]
    user.phone = params[:phone] if params[:phone]
    #
    user.password = params[:password]
    user.password_confirmation = params[:password]
    user.email = params[:email]
    if params[:make_admin]
      user.admin = true
    else
      user.season = current_season
      user.purchased = params[:slots].to_i
      user.admin = false
    end
    if user.save
      flash[:notice] = "User #{params[:email]} created."
      redirect_to admin_users_path and return
    else
      flash.now[:warning] = "Unable to create user. "
      user.errors.each do | attr, msg |
        user.errors.full_messages_for(attr).each do | m |
          flash.now[:warning] << m
        end
      end
      if params[:copy]
        redirect_to admin_users_path and return
      else
        render :new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    user = User.find(params[:id])

    authorize user
    user.firstname = params[:firstname] if params[:firstname]
    user.lastname = params[:lastname] if params[:lastname]
    user.phone = params[:phone] if params[:phone]
    user.email = params[:email]
    if params[:password]
      user.password = params[:password]
      user.password_confirmation = params[:password]
    end
    user.purchased = params[:slots].to_i
    user.save!
    flash[:notice] = "User #{params[:email]} updated."
    redirect_to admin_users_path
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    if user.admin? && User.where(admin: true).count == 1
      flash[:alert] = "Cannot delete the ONLY admin user!"
    else
      flash[:notice] = "User #{user.email} deleted."
      user.destroy
    end
    redirect_to admin_users_path
  end

  def copy
    @user = User.find(params[:id])
    authorize @user
    if @user.season.id == current_season.id
      flash[:alert] = "Not copied: User is already in current season."
      redirect_to admin_users_path and return
    end
    tmp = current_season.users.find_by email: @user.email
    if tmp 
      flash[:alert] = "Not copied: User with the same email already in current season."
      redirect_to admin_users_path and return
    end
    @user.purchased = 0
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate

  def show
    @user = User.find(params[:id])
    authorize @user
    @slots = @user.slots.sort_by {|s| s.fish_date.day }
    @num_slots = @user.slots.count
    @in_current_season = @user.season.id == current_season.id
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    user = User.find(params[:id])
    authorize user
    if params[:password]
      if params[:password_confirm] &&
          params[:password] == params[:password_confirm]
        user.password = params[:password]
        user.password_confirmation = params[:password]
      else
        flash[:alert] = "Password and confirmation do not match -- no changes made."
        redirect_to edit_user_path(user) and return
      end
    end
    user.firstname = params[:firstname] if params[:firstname] != user.firstname
    user.lastname = params[:lastname] if params[:lastname] != user.lastname
    user.phone = params[:phone] if params[:phone] != user.phone
    user.save!
    flash[:notice] = "Properties updated."
    redirect_to user_path(user)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_user.html.haml
%tr
  %td.name= user.fullname
  %td.email= user.email
  %td.phone= user.phone
  -if !user.admin?
    %td.slots= user.purchased
    - if user.used < user.purchased
      %td.slots.used= user.used
    -else
      %td.slots.used.full= user.used
  %td.link= link_to "Edit", edit_admin_user_path(user)
  - if !user.admin?
    %td.link= link_to "Show", user_path(user)
  - if user.admin || in_current
    %td.link= link_to "Delete", admin_user_path(user), 
              method: :delete,
              data: {confirm: "Deleting #{user.email} -- are you sure?"},
              id: "delete_#{user.id}"
  - if !user.admin && !in_current
    %td.link= link_to "Copy to Current", copy_admin_user_path(user)

app/views/admin/users/_users_table.html.haml
%table.adminusers
  %thead
    %tr
      %th Name
      %th Email
      %th Phone
      -if !admin
        %th Slots
        %th Used
  %tbody
    = render users, :in_current=> in_current

app/views/admin/users/copy.html.haml
%h1 Copy User to Current Season

= form_tag admin_users_path, method: :post do
  %p
    = label_tag :firstname, "First name"
    = text_field_tag :firstname, @user.firstname
  %p
    = label_tag :lastname, "Last name"
    = text_field_tag :lastname, @user.lastname
  %p
    = label_tag :phone, "Phone"
    = text_field_tag :phone, @user.phone
  %p
    = label_tag :email, "Email"
    = text_field_tag :email, @user.email, disabled: true
    = hidden_field_tag :email, @user.email
  %p
    = label_tag :password, "Password"
    = text_field_tag :password, nil
    (Must set password when copying user.)

  %p
    = label_tag :slots, "Slots"
    = number_field_tag :slots, 0, size:4
    (Must specify slots, when copying user.)

  %p
    = hidden_field_tag :copy, true
    = submit_tag "Copy"

app/views/admin/users/edit.html.haml
%h1 Edit User Info

= form_tag admin_user_path(@user), method: :patch do
  %p
    = label_tag :firstname, "First name"
    = text_field_tag :firstname, @user.firstname
  %p
    = label_tag :lastname, "Last name"
    = text_field_tag :lastname, @user.lastname
  %p
    = label_tag :phone, "Phone"
    = text_field_tag :phone, @user.phone
  %p
    = label_tag :email, "Email"
    = text_field_tag :email, @user.email
  %p
    = label_tag :password, "Password"
    = text_field_tag :password, nil
    (Leave blank, unless changing password.)

  -if !@user.admin?
    %p
      = label_tag :slots, "Slots"
      = number_field_tag :slots, @user.purchased, size:4

  %p
    = submit_tag "Update"

app/views/admin/users/index.html.haml
%h1 All Users 

= link_to "Add New User", new_admin_user_path
(to current season: #{@current.name})
%br
= link_to "Admin Home", admin_path

- if @admin_users
  %h2 
    Admin Users
  = render 'users_table', { users: @admin_users, admin: true, in_current: false }

- @seasons.each do |s|
  %h2
    Season: #{s.year}
  = render 'users_table', { users: s.users, admin: false , in_current: @current.id == s.id }

app/views/admin/users/new.html.haml
%h1 Create User

= form_tag admin_users_path, method: :post do
  %p
    = label_tag :email, "Email"
    = text_field_tag :email
  %p
    = label_tag :password, "Password"
    = text_field_tag :password
  %p
    = label_tag :slots, "Slots"
    = number_field_tag :slots, nil, size:4
  %p
    = check_box_tag :make_admin
    = label_tag :make_admin, "Give admin privileges"
  %p
    = submit_tag "Create"